---
apiVersion: v1
kind: Namespace
metadata:
  name: starboard
spec: {}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: starboard
  namespace: starboard
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: starboard
  namespace: starboard
rules:
  - apiGroups:
      - khulnasoft.github.com
    resources:
      - vulnerabilities
    verbs:
      - create
      - update
      - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: starboard
  namespace: starboard
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: starboard
subjects:
  - kind: ServiceAccount
    name: starboard
    namespace: starboard
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: starboard-khulnasoft-csp-webhook
  namespace: starboard
spec:
  replicas: 1
  selector:
    matchLabels:
      run: starboard-khulnasoft-csp-webhook
  strategy: {}
  template:
    metadata:
      labels:
        run: starboard-khulnasoft-csp-webhook
    spec:
      serviceAccountName: starboard
      containers:
        - image: khulnasoft/starboard-khulnasoft-csp-webhook:dev
          name: starboard-webhook
          env:
            - name: "STARBOARD_WEBHOOK_LOG_LEVEL"
              value: "trace"
            - name: "STARBOARD_WEBHOOK_API_ADDR"
              value: ":4000"
            - name: "STARBOARD_WEBHOOK_STARBOARD_NAMESPACE"
              value: "starboard"
          ports:
            - name: api-server
              containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: starboard-khulnasoft-csp-webhook
  namespace: starboard
spec:
  type: ClusterIP
  selector:
    run: starboard-khulnasoft-csp-webhook
  ports:
    - name: api-server
      protocol: TCP
      port: 4000
      targetPort: 4000
